//
// This file was generated by the JPA Modeler
//
package mauro.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

@Entity
public class Preventivo implements Serializable {

    @Basic
    private String descriptionGeneral;

    @OneToMany(targetEntity = LinePreventivo.class, mappedBy = "preventivo")
    private List<LinePreventivo> linePreventivoes;

    @Temporal(TemporalType.DATE)
    @Basic
    private Date dataOfCreation;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(targetEntity = Customer.class)
    private Customer customer;

    public Preventivo() {

    }

    public String getDescriptionGeneral() {
        return this.descriptionGeneral;
    }

    public void setDescriptionGeneral(String descriptionGeneral) {
        this.descriptionGeneral = descriptionGeneral;
    }

    public List<LinePreventivo> getLinePreventivoes() {
        return this.linePreventivoes;
    }

    public void setLinePreventivoes(List<LinePreventivo> linePreventivoes) {
        this.linePreventivoes = linePreventivoes;
    }

    public Date getDataOfCreation() {
        return this.dataOfCreation;
    }

    public void setDataOfCreation(Date dataOfCreation) {
        this.dataOfCreation = dataOfCreation;
    }

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Customer getCustomer() {
        return this.customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
}
